"""Fixtures for the machine-readable text parser.

Everything is synthetic. Zones are generated by ``app.services.mrz.synthetic``
from invented field values, so the suite covers the parser exhaustively without
a single real document. No personal data appears anywhere.
"""

from __future__ import annotations

from datetime import date
from typing import Dict, List

import pytest

from app.services.mrz import TD3, build_mrz
from app.services.mrz.icao import ICAOMRZParser

#: Century resolution depends on "now", so the suite pins a reference date and
#: never depends on the day it happens to run.
REFERENCE_DATE = date(2026, 9, 1)

#: Invented field values used across the suite. UTO is the ICAO example code
#: reserved for specimens, and the rest is obviously fictional.
SPECIMEN: Dict[str, str] = {
    "document_code": "P",
    "issuing_state": "UTO",
    "surname": "SPECIMEN",
    "given_names": "SAMPLE TEST",
    "document_number": "AB1234567",
    "nationality": "UTO",
    "birth_date": "800101",
    "sex": "M",
    "expiry_date": "301231",
    "optional_data": "",
}

#: The worked example published in ICAO Doc 9303 itself.
ICAO_TD3_SPECIMEN: List[str] = [
    "P<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<",
    "L898902C36UTO7408122F1204159ZE184226B<<<<<10",
]
ICAO_TD2_SPECIMEN: List[str] = [
    "I<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<",
    "D231458907UTO7408122F1204159<<<<<<<6",
]
ICAO_TD1_SPECIMEN: List[str] = [
    "I<UTOD231458907<<<<<<<<<<<<<<<",
    "7408122F1204159UTO<<<<<<<<<<<6",
    "ERIKSSON<<ANNA<MARIA<<<<<<<<<<",
]


@pytest.fixture
def parser() -> ICAOMRZParser:
    return ICAOMRZParser(reference_date=REFERENCE_DATE)


@pytest.fixture
def specimen() -> Dict[str, str]:
    return dict(SPECIMEN)


@pytest.fixture
def td3_lines() -> List[str]:
    return build_mrz(SPECIMEN, TD3)


def make_lines(mrz_type: str = TD3, **overrides: str) -> List[str]:
    """Build a synthetic zone with some fields overridden."""
    return build_mrz({**SPECIMEN, **overrides}, mrz_type)
